hello/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path("", views.index, name="index"),
    path("task", views.task, name="task"),
    path("<str:name>", views.greet, name="greet"),
    

]

tasks/urls.py
from django.urls import path
from . import views

app_name= 'tasks'

urlpatterns =[
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    # path("<str:name>", views.greet, name="greet"),
    

]

trading/urls.py
from django.contrib import admin
from django.urls import path, include

# them vao import anh
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('portfolios.urls')),
    path('hello/', include('hello.urls')),
    path('tasks/', include('tasks.urls'))
    
]

# test upload anh
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

tasks/models.py
from django.db import models

# Create your models here.

tasks/views.py
from django.shortcuts import render
from django import forms
# Create your views here.


tasks = ['Toa', 'cam', 'chuoi']

class NewTaskForm(forms.Form):
    task = forms.CharField(label='new task', max_length=50)
    priority = forms.IntegerField(label='priority', min_value=1, max_value=3)

def index(request):
    return render(request, 'tasks/index.html', {'tasks': tasks})

def add(request):
    return render(request, 'tasks/add.html', {'form': NewTaskForm()})

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block title %}
    
{% endblock %}

{% block main %}
<h1>Add a new task</h1>
<form method="post" action="{% url 'tasks:add' %}">
    {% csrf_token %}
  {{form}}
  <input type="submit">
</form>    
<a href="{% url 'tasks:index' %}">View all tasks</a>

{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block title %}
    
{% endblock %}

{% block main %}

       <h1>tasks</h1>
       <ul>
        {% for task in tasks %}
          <li>{{ task }} </li>
        {% endfor %}
      </ul>
      <a href="{% url 'tasks:add' %}">Add a task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title></title>
  </head>
  <body>
    {% block main %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>