account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'account'

urlpatterns = [
    # post views
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    # path("login/", views.user_login, name='login'), # tự code
    path('login/', auth_views.LoginView.as_view(), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/',
        auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done')),
        name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path("", views.index, name="index"),
    path("task", views.task, name="task"),
    path("<str:name>", views.greet, name="greet"),
    

]

portfolios/urls.py
from django.urls import path
from . import views

app_name= 'portfolios'

urlpatterns =[
    path("", views.index, name="index"),
    path("danhmuc", views.my_portfolio, name="my_portfolio"),
    path("buy", views.buy, name="buy"),
    path("sell", views.sell, name="sell"),
    path("history", views.history, name="history")
    

]

trading/urls.py
from django.contrib import admin
from django.urls import path, include

# them vao import anh
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('portfolios.urls')),
    path('hello/', include('hello.urls')),
    path('tasks/', include('tasks.urls'))
    
]

# test upload anh
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title></title>
  </head>
  <body>

   

    <header class="p-3 mb-3 border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
            <!-- <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg> -->
            <img class="bi me-2" width="25" height="25" src="https://danhmuc.herokuapp.com/assets/icon/032-ipo-c58a214a95fc73ad516fb2e5a57820489ca90e8bd09e8cc0a3ad17bc0b37e33d.png">
            <span class="fs-4">Investing</span>
          </a>
          {% if request.user.is_authenticated %} 
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'portfolios:my_portfolio' %}" class="nav-link px-2 link-secondary">Danh mục</a></li>
            <li><a href="{% url 'portfolios:buy' %}" class="nav-link px-2 link-dark">Buy</a></li>
            <li><a href="{% url 'portfolios:sell' %}" class="nav-link px-2 link-dark">Sell</a></li>
            <li><a href="{% url 'portfolios:history' %}" class="nav-link px-2 link-dark">History</a></li>
       
          </ul>
  
          

          <form action="/quote" method="post" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            
                <input autocomplete="off" autofocus class="form-control" name="symbol" placeholder="Stock Symbol" type="search">
                <!-- <input type="search" class="form-control" placeholder="Search..." aria-label="Search"> -->
            <!-- <button class="btn btn-primary" type="submit" style="visibility: hidden;">Quote</button> -->
          </form>

          <!-- <div class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
            <input class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Type to search...">
            <datalist id="datalistOptions">
              <option value="San Francisco">
              <option value="New York">
              <option value="Seattle">
              <option value="Los Angeles">
              <option value="Chicago">
            </datalist>
          </div> -->
  
          <div class="dropdown text-end">
            <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjUW21q9KKxvoQL3Iy0NLPywJ8xoRg7uDGUw&usqp=CAU" alt="rocket" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
              <li><a class="dropdown-item" href="{% url 'account:logout' %}">Change Password</a></li>
              <li><a class="dropdown-item" href="#">Settings</a></li>
              <li><a class="dropdown-item" href="#">Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'account:logout' %}">Sign out</a></li>
            </ul>
          </div>
          {% else %}
          
          

          <div class="col-md-3 text-end">
            <a href="{% url 'account:login' %}" class="btn btn-secondary me-2 ">Login</a>
            <button type="button" class="btn btn-primary">Sign-up</button>
          </div>

          
          
          {% endif %}
          
        </div>
      </div>
    </header>
    
    {% if messages %}      
          {% for msg in messages %}              
              <div class="alert alert-{{msg.level_tag}} alert-dismissible fade show" role="alert"> 
                <strong>{{msg.message}}</strong> You just placed an order.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>    
          {% endfor %}  
    {% endif %}


  <main class="container">
      {% block main %}{% endblock %}
  </main>

  <footer class="small text-center text-muted mt-5">
      Data provided by <a href="https://iextrading.com/developer">choncophieu</a>
  </footer>
  
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

templates/react_layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello World</title>
    
  </head>
  <body>
    <div id="app"></div>
    <!-- We will put our React component inside this div. -->
    <div id="like_button_container"></div>


    <script type="text/babel">
        
      
      function Hello(props) {
        const x = 1;
        const y = 2;
        return (
          <div> hello {props.name} </div>
        )
      }

      function App() {
        const [count, setCount] = React.useState(0)
        function updateCount(){
          setCount(count+1)
        }
        return (
          <div>
            < Hello name="test Name" />
            <div>{count}</div>
            <button onClick={updateCount}> edit </button>
            <input />
          </div>
        )
      }
      const container = document.getElementById('app');

    //   document.addEventListener('DOMContentLoaded', function() {
    //         ReactDOM.render(
    //             < App />, container
    //         );
    //     });

      ReactDOM.render(
        < App />, container
      );
    </script>

    <script src="https://unpkg.com/react@17/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
    <!-- <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-select/5.2.1/index-30b509fd.cjs.prod.min.js"></script>
    
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

  </body>
</html>
        